### ISSUE TITLE
How to cross compile this project?

### ISSUE THREAD

**Issue by adfnekc** [liudf0716/xfrpc#1]
i want cross compile this project ,that compile from x64 to arm; what should i do?

**Comment by naY9yjoS6ZqhOd35sIFH** [comment]
and,how about port to netbsd/vax,i have environment to build this

**Comment by liudf0716** [comment]
@adfnekc I think just compile like x86, if u have arm ubuntu system. or like openwrt which provide toolchain to compile xfrpc
@naY9yjoS6ZqhOd35sIFH I didn't compile in netbsd/vax, however I think xfprc can be compile just like in ubuntu
