### ISSUE TITLE
客户端与服务器断开后无法重新连接服务器

### ISSUE THREAD

**Issue by A-lullaby** [liudf0716/xfrpc#18]
![image](https://user-images.githubusercontent.com/110453668/209634695-c029e9ef-815e-482d-8e35-c40d2ce722d0.png)
如何复现：1.在虚拟机下安装xfrpc，然后与frps建立连接
                  2.断开虚拟机网络（或修改ip）1-3分钟，然后重新连接虚拟机网络

**Comment by liudf0716** [comment]
fixed
