### ISSUE TITLE
程序断网重连出现CPU占满情况

### ISSUE THREAD

**Issue by A-lullaby** [liudf0716/xfrpc#19]
![0b147dd43d584ca6cfe760f70fe92fe](https://user-images.githubusercontent.com/110453668/210479821-01ea6c7a-2ce6-4483-b67a-12c380bbaf16.png)

**Comment by liudf0716** [comment]
应该是在清除client和stream资源时，有死循环被触发

**Comment by helintongh** [comment]
能否给出详细的操作过程呢?
比如你的配置,操作系统版本等.方便复现然后修复相应的bug

**Comment by helintongh** [comment]
在uibuntu22.04环境下,测试xfrpc的tcp配置和http配置。分别断网三次down掉网卡又up网卡。xfrpc均能重新连上frps且未出现xfrpc占用cpu100%的bug。

xfrpc配置如下:
[common]
server_addr = 192.168.157.1
server_port = 7000

[http]
type = http
local_port = 80
custom_domains = www.example.com

[https]
type = https
local_port = 443
custom_domains = www.example.com

frps配置如下：
[common]
bind_port = 7000
vhost_http_port = 80
vhost_https_port = 443
但是当出现如下打印
[7][Wed Jan  4 15:19:36 2023][4852](control.c:128) new client through tcp mux: 5
[7][Wed Jan  4 15:19:36 2023][4852](control.c:690) send plain msg ----> [w: { "run_id": "000C29D72E1E" }]
[6][Wed Jan  4 15:21:07 2023][4852](control.c:248)  interval [91] greater than heartbeat_timeout [90]
[7][Wed Jan  4 15:21:07 2023][4852](client.c:182) free client 5
**[6][Wed Jan  4 15:21:07 2023][4852](control.c:653) connect server [192.168.157.1:7000]...**

注意最后一行,主线的xfrpc卡在了这最后一行再也无法回连到frps上面。因此猜测原因在于xfrpc一直尝试回连导致cpu占用100%。这个bug可以试下利用另一个线程来监控xfrpc的连接状态超时就重启xfrpc。

**Comment by liudf0716** [comment]
是因为有死循环导致，代码有bug导致

**Comment by A-lullaby** [comment]
不是因为断网重连进入的死循环吗？&nbsp;


浪
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月5日(星期四) 上午9:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liudf0716/xfrpc] 程序断网重连出现CPU占满情况 (Issue #19)





 
是因为有死循环导致，代码有bug导致

**Comment by liudf0716** [comment]
@A-lullaby 断网会导致循环连接，但有sleep，不会导致cpu 100%

**Comment by A-lullaby** [comment]
了解了解&nbsp;


浪
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月5日(星期四) 上午9:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liudf0716/xfrpc] 程序断网重连出现CPU占满情况 (Issue #19)





 
@A-lullaby 断网会导致循环连接，但有sleep，不会导致cpu 100%

**Comment by liudf0716** [comment]
是uthash宏使用错误的问题
