### ISSUE TITLE
服务端只支持IP，不支持域名，frpc支持域名。

### ISSUE THREAD

**Issue by vpei** [liudf0716/xfrpc#4]
服务端只支持IP，不支持域名，frpc支持域名。

**Comment by liudf0716** [comment]
好的，尽快加上

**Comment by vpei** [comment]
> 经验证，支持域名

我用的是在Openwrt上面的luci-app-xfrpc，那个输入服务器地址的地方，都不让输入域名，看文本类型给限制成ipaddr。/etc/init.d/xfrp文件中
		uci_validate_section xfrpc xfrp "$name" \
				'server_addr:ipaddr' \
				'server_port:uinteger' \
				'token:string:'	
我填入域名，后来到配置文件中（/var/etc/xfrpc.ini），就给过滤没了。

**Comment by vpei** [comment]
我刚修改xfrpc/files/xfrpc.init文件中，'server_addr:ipaddr'  为 'server_addr:string'  , 现在已经可以使用域名。

**Comment by vpei** [comment]
是openwrt仓库的代码出问题了，呵呵。

**Comment by liudf0716** [comment]
@vpei openwrt的luci配置的确有这个问题，会尽快解决。
