### ISSUE TITLE
类型为tcpmux会出现不支持的情况

### ISSUE THREAD

**Issue by a158566154** [liudf0716/xfrpc#48]
将配置文件中的type为tcpmux时会出现proxy service type tcpmux is not supportted.

查看readme是发现支持的，采用最新版的源码，交叉编译到padavan中使用。pdavan内核版本3.4.x
配置如下：
![image](https://github.com/liudf0716/xfrpc/assets/59275493/41ced2b5-c08e-4d6d-ab25-1c503ec05249)

**Comment by liudf0716** [comment]
@a158566154 是的，xfrpc不支持tmux代理服务，只是支持与frps通过tmux协议通信
