### ISSUE TITLE
A 32bit cpu incompatibility problem about timestamp.

### ISSUE THREAD

**Issue by mumianbaba** [liudf0716/xfrpc#52]
```c
struct login {
	char		*version;
	char		*hostname;
	char 		*os;
	char		*arch;
	char 		*user;
	char 		*privilege_key;
	long int 	timestamp;
	char 		*run_id;
	char		*metas;
	int 		pool_count;

	/* fields not need json marshal */
	int			logged;		//0 not login 1:logged
};
```
在login.h文件中的结构体login 中的timestamp成员定义为long int类型，在32位架构CPU中，该类型为4 bytes。在msg.c文件的`login_request_marshal`函数中调用`JSON_MARSHAL_TYPE(j_login_req, "timestamp", int64, lg->timestamp);`。int64类型是8 bytes。存在兼容性问题。
建议使用time_t类型，然后根据sizeof(time_t)来选择传入的是int64还是int。cJOSN就做的很好，直接使用double存所有的数字。

**Comment by liudf0716** [comment]
谢谢详细的分析！
