### ISSUE TITLE
1.11.587版本内存占用会不断增加

### ISSUE THREAD

**Issue by gzliurc** [liudf0716/xfrpc#6]
编译测试了x86_64和arm下的版本，都存在内存不断增加的情况，应该有明显的内存泄露

初始内存情况：3848K
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 1525 vlinker   20   0   16404   3848   3444 S   0.0  0.0   0:00.00 xfrpc

刷新一次网页后：内存升到6.8M
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 1525 vlinker   20   0   19352   6808   3444 S   0.0  0.0   0:00.15 xfrpc

刷新第五次以后，内存升到17M
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 1525 vlinker   20   0   29384  16840   3444 S   0.0  0.1   0:00.73 xfrpc

继续刷新网页内存很快就可以突破100M，停止访问后内存不会下降

补充其他依赖版本号：
libevent-2.1.12-stable.tar.gz
json-c-json-c-0.16-20220414.tar.gz
openssl-1.1.1s.tar.gz

**Comment by liudf0716** [comment]
@gzliurc 感谢反馈，我验证一下

**Comment by liudf0716** [comment]
@gzliurc master分支已经解决了内存泄露的问题，谢谢反馈！

**Comment by gzliurc** [comment]
> 

经测试，内存泄漏问题已解决

**Comment by liudf0716** [comment]
@gzliurc 谢谢反馈及验证！
