### ISSUE TITLE
在GCC14上交叉编译失败

### ISSUE THREAD

**Issue by imzlh** [liudf0716/xfrpc#68]
<img width="857" alt="image" src="https://github.com/user-attachments/assets/e0f1623c-1d69-46b8-8e15-2c3876fccb1f">

不知道是不是我的muslgcc问题，我用的是自己编译的 armv7l-linux-musleabi-gcc-14.2.0

**Comment by qnxsgwy** [comment]
同样遇到类似问题，Ubuntu24.04，git下来项目，第一次测试动态链接编译正常，然后测试静态编译报错如下
/usr/bin/ld: msg.c:(.text+0x611): undefined reference to `json_object_put'
/usr/bin/ld: msg.c:(.text+0x6c0): undefined reference to `json_object_new_string'
连接器找不到cjson库

然后测试静态交叉编译，报错：
CMake Error at cmake/Modules/FindLibEvent.cmake:34 (message):
  Could NOT find libevent.

再测试动态链接编译，报错：
msg.c:163:55: error: passing argument 2 of ‘get_auth_key’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  163 |         char *auth_key = get_auth_key(cf->auth_token, &lg->timestamp);
      |                                                       ^~~~~~~~~~~~~~
      |                                                       |
      |                                                       time_t * {aka long long int *}
/home/guo/xfrpc/msg.c:129:43: note: expected ‘long int *’ but argument is of type ‘time_t *’ {aka ‘long long int *’}
  129 | get_auth_key(const char *token, long int *timestamp)
      |                                 ~~~~~~~~~~^~~~~~~~~
cc1: all warnings being treated as errors

总结一下就是工程git回来直接动态链接编译，没有问题。直接静态链接编译连接器会报找不到cjson库，直接交叉静态编译cmake会报Could NOT find libevent，中间一旦改编译模式应该是因为没有做clean，就会导致更多稀奇古怪错误。

感觉还是编译脚本对静态链接和交叉编译处理的不完善导致的。

**Comment by qnxsgwy** [comment]
刚才测试了一下master分支10月份的版本，这个版本直接静态链接编译不会报错，可以生成二进制文件成功运行，但是交叉编译cmake还是报错。项目的代码应该是没问题的，应该是依赖的库比较多，编译脚本没做好，导致的问题。

**Comment by liudf0716** [comment]
交叉编译失败的问题后面有时间再解决

**Comment by imzlh** [comment]
弱弱地问一句，还是这个问题算谁的锅

<img width="797" alt="image" src="https://github.com/user-attachments/assets/381278d3-3e64-42cd-93a9-266ea9f0e630">

**Comment by liudf0716** [comment]
@imzlh 数据类型转换的问题，gcc-14的数据类型转换的要求更严，本来是warning的报成错误了。我用gcc-14编译没遇到这个问题，你是用的xfrpc的代码吗？还是你自己改的？

**Comment by imzlh** [comment]
> @imzlh 数据类型转换的问题，gcc-14的数据类型转换的要求更严，本来是warning的报成错误了。我用gcc-14编译没遇到这个问题，你是用的xfrpc的代码吗？还是你自己改的？

xfrpc git master，不是我改的

**Comment by helintongh** [comment]
> > @imzlh 数据类型转换的问题，gcc-14的数据类型转换的要求更严，本来是warning的报成错误了。我用gcc-14编译没遇到这个问题，你是用的xfrpc的代码吗？还是你自己改的？
> 
> xfrpc git master，不是我改的

给一下交叉编译器版本。有时间我可以改一下

**Comment by imzlh** [comment]
```
➜  iz armv7l-linux-musleabi-gcc-14.2.0 -v
Using built-in specs.
COLLECT_GCC=armv7l-linux-musleabi-gcc-14.2.0
COLLECT_LTO_WRAPPER=/usr/local/bin/../libexec/gcc/armv7l-linux-musleabi/14.2.0/lto-wrapper
Target: armv7l-linux-musleabi
Configured with: ../src_gcc/configure --enable-languages=c,c++,fortran --disable-bootstrap --disable-assembly --disable-werror --target=armv7l-linux-musleabi --prefix= --libdir=/lib --disable-multilib --with-sysroot=/armv7l-linux-musleabi --enable-tls --disable-libmudflap --disable-libsanitizer --disable-gnu-indirect-function --disable-libmpx --enable-initfini-array --enable-libstdcxx-time=rt --enable-deterministic-archives --enable-libstdcxx-time --enable-libquadmath --enable-libquadmath-support --disable-decimal-float --with-build-sysroot=/root/musl-cross-make/build/local/armv7l-linux-musleabi/obj_sysroot AR_FOR_TARGET=/root/musl-cross-make/build/local/armv7l-linux-musleabi/obj_binutils/binutils/ar AS_FOR_TARGET=/root/musl-cross-make/build/local/armv7l-linux-musleabi/obj_binutils/gas/as-new LD_FOR_TARGET=/root/musl-cross-make/build/local/armv7l-linux-musleabi/obj_binutils/ld/ld-new NM_FOR_TARGET=/root/musl-cross-make/build/local/armv7l-linux-musleabi/obj_binutils/binutils/nm-new OBJCOPY_FOR_TARGET=/root/musl-cross-make/build/local/armv7l-linux-musleabi/obj_binutils/binutils/objcopy OBJDUMP_FOR_TARGET=/root/musl-cross-make/build/local/armv7l-linux-musleabi/obj_binutils/binutils/objdump RANLIB_FOR_TARGET=/root/musl-cross-make/build/local/armv7l-linux-musleabi/obj_binutils/binutils/ranlib READELF_FOR_TARGET=/root/musl-cross-make/build/local/armv7l-linux-musleabi/obj_binutils/binutils/readelf STRIP_FOR_TARGET=/root/musl-cross-make/build/local/armv7l-linux-musleabi/obj_binutils/binutils/strip-new --build=x86_64-pc-linux-musl --host=x86_64-pc-linux-musl
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 14.2.0 (GCC)
```

**Comment by qnxsgwy** [comment]
新反馈一下，也算是给也算是给之后遇到问题的分享些经验，经过尝试，现在已经成功完成mipsel架构下静态交叉编译，即使使用老旧的OpenWrt-Toolchain-ramips-for-mipsel_24kec+dsp-gcc-4.8-linaro_uClibc-0.9.33.2交叉编译工具链，依旧可以正常编译，在MT76X8平台上实测可以正常运行，其他平台应该更不成问题，确定是目前自带的编译脚本问题。
编译时需要删除CMakeLists里对依赖库的自动检测编译相关内容，手动对thirdparty文件夹下的四个依赖库使用交叉编译工具链静态编译，特别注意：openssl使用no-asm no-async shared选项；libevent不要使用cmake生成makeflie，会各种报错，或者生成错误的makeflie（估计是里面的CMakeLists对交叉编译的处理不好，我试着改了改还是不行），改用configure脚本生成makeflie；还有一旦出错一定要记得clean一下修改错误再重新编译，不clean直接重新编译也会出奇怪问题。然后将所有生成的.a静态库手动拷贝到lib文件夹，再对程序本体进行交叉编译就行。
另外感谢作者提供这么好的项目，全部静态交叉编译，strip之后，程序大小只有3m左右，确实对嵌入式设备开发十分友好。
