### ISSUE TITLE
stream已经被释放了导致的段错误

### ISSUE THREAD

**Issue by A-lullaby** [liudf0716/xfrpc#7]
![bdbf797683ee0e4754e597426baa3db](https://user-images.githubusercontent.com/110453668/206128021-b7888e3c-71c1-4e3e-b79b-36e2cc3c4543.png)

**Comment by jake-esa** [comment]
不断访问本地服务，到达一定的时间程序段错误

**Comment by liudf0716** [comment]
@jake-esa 好的，有空我看看，谢谢反馈！
